apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

commonLabels:
  environment: azure
  provider: azure

patches:
  # Service patches for Azure
  - path: patches/services-azure.yaml
    target:
      kind: Service

  # Storage class patches for Azure
  - path: patches/storage-azure.yaml
    target:
      kind: PersistentVolumeClaim

images:
  - name: itzg/minecraft-server
    newTag: latest
  - name: itzg/minecraft-bedrock-server
    newTag: latest
