apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

commonLabels:
  environment: aws
  provider: aws

patches:
  # Service patches for AWS
  - path: patches/services-aws.yaml
    target:
      kind: Service

  # Storage class patches for AWS
  - path: patches/storage-aws.yaml
    target:
      kind: PersistentVolumeClaim

images:
  - name: itzg/minecraft-server
    newTag: latest
  - name: itzg/minecraft-bedrock-server
    newTag: latest
